config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :categories, only: [:show, :index, :edit, :new]
    resources :images, only: [:create, :new, :index]
  end

  resources :categories, only: [:show, :index, :update, :destroy, :create]

  resources :users do
    resources :movies
  end

  resources :movies do
    post "/ratings", to: "ratings#create"
  end

  post "/movie-images", to: "movieimages#create"

  get "/users/:id/movies", to: "user#index"

  get "/admin/dashboard", to: "admin/dashboard#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name, :image
  validates_uniqueness_of :name
  has_many :movies, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of :url
  validates_uniqueness_of :url
  has_many :movie_images
  has_many :movies, through: :movie_images
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates_presence_of :title, :description
  has_many :movie_images, dependent: :destroy
  has_many :images, through: :movie_images
  belongs_to :category
  has_many :ratings
  belongs_to :user

  def total_rating
    ratings.sum(:value)
  end
end

app/models/movie_image.rb
class MovieImage < ApplicationRecord
  validates_uniqueness_of :movie_id, scope: :image_id
  belongs_to :movie
  belongs_to :image
end

app/models/rating.rb
class Rating < ApplicationRecord
  validates_uniqueness_of :movie_id, scope: :user_id
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :email, :username, :password
  validates_uniqueness_of :email, :username
  has_many :ratings, dependent: :destroy
  has_many :movies, dependent: :destroy

  enum role: ["default", "admin"]

  def total_ratings
    ratings.sum(:value)
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  def new
    @image = Image.new
  end

  def index
    @images = Image.all
  end

  def create
    render :index if !current_admin?
    @image = Image.new(image_params)
    if @image.save
      redirect_to admin_dashboard_path
    else
      render :new
    end
  end

  private

    def image_params
      params.require(:image).permit(:url)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :user_owned?, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def user_owned?
    @movie.user_id == current_user.id
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    render :index if !current_admin?
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_category_path(@category)
    else
      render :new
    end
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    if @category.save
      redirect_to admin_category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to admin_categories_path
  end

  private

    def category_params
      params.require(:category).permit(:name, :image)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def edit
    @images = Image.all
    @movie = current_user.movies.find(params[:id])
  end

  def new
    @images = Image.all
    @movie = Movie.new
  end

  def index
    if params[:user_id]
      user = User.find(params[:user_id])
      @movies = user.movies
    else
      @movies = Movie.all
    end
  end

  def show
    if !current_user
      redirect_to movies_path
    else
      @movie = Movie.find(params[:id])
    end
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)
    if @movie.save
      movie_image = MovieImage.where(movie_id: params[:id])
      movie_image.destroy_all
      create_movie_image_relationship if params[:movie][:image_ids]
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    movie = Movie.find(params[:id])
    rating = Rating.where(movie_id: params[:id])
    rating.destroy_all
    movie_image = MovieImage.where(movie_id: params[:id])
    movie_image.destroy_all
    movie.destroy
    redirect_to user_movies_path(current_user)
  end

  def create
    @movie = current_user.movies.new(movie_params)
    if @movie.save
      create_movie_image_relationship if params[:movie][:image_ids]
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  private

    def movie_params
      params.require(:movie).permit(:title, :description, :category_id, :user_id)
    end

    def create_movie_image_relationship
      params[:movie][:image_ids].each do |image_id|
        MovieImage.create!(movie_id: @movie.id, image_id: image_id) if !image_id.empty?
      end
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create
    movie = Movie.find(params[:movie_id])
    current_user.ratings.create(movie: movie)

    redirect_to movie_path(movie)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def update
    user = current_user
    user.update(user_params)
    if user.save
      redirect_to user_path(user)
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/_form.html.erb
<%= form_for @image do |f| %>

<%= f.label :url %>
<%= f.text_field :url %>

<%= f.submit %>

<% end %>

app/views/admin/dashboard/_nav.html.erb
<nav class="nav">
  <section class="nav-links">
    <%= link_to "Movies", movies_path %>
    <%= link_to "Categories", categories_path %>
  </section>
  <section class="nav-user">
    Welcome, <%= current_user.username %>!
    <%= link_to "My Movie Ideas", user_movies_path(current_user) %>
    <%= link_to "Admin Dashboard", admin_dashboard_path if current_admin? %>
    <%= link_to "Log Out", logout_path, method: "delete" %>
  </section>
</nav>

app/views/admin/dashboard/index.html.erb
<header class="header">The power is yours, <%= current_user.username %></header>
<header class="header"><%= link_to "Manage Categories", admin_categories_path %></header>
<header class="header"> <%= link_to "Manage Images", admin_images_path %></header>

app/views/movies/_create.html.erb
<section class="create">
  Have your own idea? <br><%= link_to "Create it!", new_movie_path %>
</section>

app/views/movies/_delete.html.erb
<section class="utility-delete">
  <%= link_to "Delete", movie_path(@movie), method: "delete" %>
</section>

app/views/movies/_edit.html.erb
<section class="utility-edit">
  <%= link_to "Edit", edit_movie_path(@movie) %>
</section>

app/views/movies/_form.html.erb
<section class="form-movie-container">
  <center><%= form_for @movie do |f| %>

  <%= f.label :title %>
  <br>
  <%= f.text_field :title, :class => "form-field" %>
  <br>
  <%= f.label :description %>
  <br>
  <%= f.text_field :description, :class => "form-field" %>
  <br>
  <%= f.label :category %>
  <br>
  <%= f.collection_select :category_id, Category.all, :id, :name %></center>

  <br>Select the images that inspire you (Pick at least one):
  <section class="images">
    <%= hidden_field_tag 'movie[image_ids][]', nil %>
    <% @images.each do |image| %>
    <section class="image">
      <%= check_box_tag('movie[image_ids][]', image.id, @movie.image_ids.include?(image.id), id: "image-#{image.id}") %>
      <label for=<%= "image-#{image.id}" %>><%= image_tag image.url, width: 100 %></label>
    </section>
    <% end %>
  </section>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  <section class="submit-container">
    <%= f.submit :class => "submit-button" %>
  </section>
  <% end %>
</section>

app/views/movies/_nav.html.erb
<nav class="nav">
  <section class="nav-links">
    <%= link_to "Movies", movies_path %>
    <%= link_to "Categories", categories_path %>
  </section>
  <section class="nav-user">
    Welcome, <%= current_user.username %>!
    <%= link_to "My Movie Ideas", user_movies_path(current_user) %>
    <%= link_to "Admin Dashboard", admin_dashboard_path if current_admin? %>
    <%= link_to "Log Out", logout_path, method: "delete" %>
  </section>
</nav>

app/views/movies/edit.html.erb
<header class="header">Edit Movie</header>
<%= render partial: "form" %>

app/views/movies/index.html.erb
<section class="movie-container">
  <header class="header">
    All Movie Ideas
  </header>
  <%= render partial: "create" if current_user %>
  <% @movies.each do |movie| %>
    <section class="movie-card">
      <section class="movie">
        <center class="title"><%= link_to movie.title, movie_path(movie) %></center>
        <center><%= movie.description %><br></center>
        Total Ratings: <%= movie.total_rating %><br>
      </section>
    </section>
  <% end %>
</section>

app/views/movies/new.html.erb
<header class="header">Create Movie</header>
<%= render partial: "form" %>

app/views/movies/show.html.erb
<section class="movie-container">
  <header class="header">Movie Idea by <%= @movie.user.username %></header>
    <section class="movie-card">
      <section class="movie">
        <center class="title"><%= link_to @movie.title, movie_path(@movie) %></center>
        <center><%= @movie.description %><br></center>
        <center>Total Ratings: <%= @movie.total_rating %><br></center>
        <center>Category: <%= @movie.category.name %></center>
        <section class="upvote">
          <%= button_to "Upvote", movie_ratings_path(@movie) %><br>
        </section>
        <section class="utility">
          <%= render partial: "edit" if user_owned? %>
          <%= render partial: "delete" if user_owned? || current_admin? %>
        </section>
      </section>
    </section>
  </section>
  <section class="images">
    <header class="header">
      Screenshots
    </header>
    <section class="image">
      <% @movie.images.each do |image| %>
        <img src="<%= image.url %>">
      <% end %>
    </section>
  </section>
</section>

app/views/welcome/index.html.erb
<section class="home">
  <header class="header">
    <center>Welcome <br> to  the <br> Movie  Idea  Box</center>
  </header>
  <center>New user?<br> <%= link_to "Sign up", new_user_path %><br>
  Returning user?<br> <%= link_to "Log in", login_path %></center>
</section>