config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :categories, only: [:show, :index, :edit, :new]
    resources :images, only: [:create, :new, :index]
  end

  resources :categories, only: [:show, :index, :update, :destroy, :create]

  resources :users do
    resources :movies
  end

  resources :movies do
    post "/ratings", to: "ratings#create"
  end

  post "/movie-images", to: "movieimages#create"

  get "/users/:id/movies", to: "user#index"

  get "/admin/dashboard", to: "admin/dashboard#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name, :image
  validates_uniqueness_of :name
  has_many :movies, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of :url
  validates_uniqueness_of :url
  has_many :movie_images
  has_many :movies, through: :movie_images
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates_presence_of :title, :description
  has_many :movie_images, dependent: :destroy
  has_many :images, through: :movie_images
  belongs_to :category
  has_many :ratings
  belongs_to :user

  def total_rating
    ratings.sum(:value)
  end
end

app/models/movie_image.rb
class MovieImage < ApplicationRecord
  validates_uniqueness_of :movie_id, scope: :image_id
  belongs_to :movie
  belongs_to :image
end

app/models/rating.rb
class Rating < ApplicationRecord
  validates_uniqueness_of :movie_id, scope: :user_id
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :email, :username, :password
  validates_uniqueness_of :email, :username
  has_many :ratings, dependent: :destroy
  has_many :movies, dependent: :destroy

  enum role: ["default", "admin"]

  def total_ratings
    ratings.sum(:value)
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  def new
    @image = Image.new
  end

  def index
    @images = Image.all
  end

  def create
    render :index if !current_admin?
    @image = Image.new(image_params)
    if @image.save
      redirect_to admin_dashboard_path
    else
      render :new
    end
  end

  private

    def image_params
      params.require(:image).permit(:url)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :user_owned?, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def user_owned?
    @movie.user_id == current_user.id
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    render :index if !current_admin?
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_category_path(@category)
    else
      render :new
    end
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    if @category.save
      redirect_to admin_category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to admin_categories_path
  end

  private

    def category_params
      params.require(:category).permit(:name, :image)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def edit
    @images = Image.all
    @movie = current_user.movies.find(params[:id])
  end

  def new
    @images = Image.all
    @movie = Movie.new
  end

  def index
    if params[:user_id]
      user = User.find(params[:user_id])
      @movies = user.movies
    else
      @movies = Movie.all
    end
  end

  def show
    if !current_user
      redirect_to movies_path
    else
      @movie = Movie.find(params[:id])
    end
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)
    if @movie.save
      movie_image = MovieImage.where(movie_id: params[:id])
      movie_image.destroy_all
      create_movie_image_relationship if params[:movie][:image_ids]
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    movie = Movie.find(params[:id])
    rating = Rating.where(movie_id: params[:id])
    rating.destroy_all
    movie_image = MovieImage.where(movie_id: params[:id])
    movie_image.destroy_all
    movie.destroy
    redirect_to user_movies_path(current_user)
  end

  def create
    @movie = current_user.movies.new(movie_params)
    if @movie.save
      create_movie_image_relationship if params[:movie][:image_ids]
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  private

    def movie_params
      params.require(:movie).permit(:title, :description, :category_id, :user_id)
    end

    def create_movie_image_relationship
      params[:movie][:image_ids].each do |image_id|
        MovieImage.create!(movie_id: @movie.id, image_id: image_id) if !image_id.empty?
      end
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create
    movie = Movie.find(params[:movie_id])
    current_user.ratings.create(movie: movie)

    redirect_to movie_path(movie)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def update
    user = current_user
    user.update(user_params)
    if user.save
      redirect_to user_path(user)
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/_form.html.erb
<section class="form-container">
  <%= form_for @category do |f| %>

  <%= f.label :name %>
  <br>
  <%= f.text_field :name, :class => "form-field" %>

  <%= f.label :image %>
  <br>
  <%= f.text_field :image, :class => "form-field" %>

  <section class="submit-container">
    <%= f.submit :class => "submit-button" %>
  </section>

  <% end %>
</section>

app/views/admin/categories/_nav.html.erb
<nav class="nav">
  <section class="nav-links">
    <%= link_to "Movies", movies_path %>
    <%= link_to "Categories", categories_path %>
  </section>
  <section class="nav-user">
    Welcome, <%= current_user.username %>!
    <%= link_to "My Movie Ideas", user_movies_path(current_user) %>
    <%= link_to "Admin Dashboard", admin_dashboard_path if current_admin? %>
    <%= link_to "Log Out", logout_path, method: "delete" %>
  </section>
</nav>

app/views/admin/categories/edit.html.erb
<header class="header">Edit Category</header>
<%= render partial: "form" %>
<section class="sub-header"> <%= link_to "Back to Admin Dashboard", admin_dashboard_path %></section>

app/views/admin/categories/index.html.erb
<section class="categories">
  <header class="header">Admin Categories</header>
  <header class="sub-header">Don't see what you are looking for? <br><%= link_to "Create New Category", new_admin_category_path %></header>
  <% @categories.each do |category|  %>
  <section class="category">
    <section class="category-title">
      <center><%= link_to category.name, category_path(category) %></center>
    </section>
    <section class="utility">
      <section class="utility-edit">
        <%= link_to "Edit", edit_admin_category_path(category) %>
      </section>
      <section class="utility-delete">
        <%= link_to "Delete", category_path(category), method: "delete" %>
      </section>
    </section>
  </section>
<% end %>
</section>

app/views/admin/categories/new.html.erb
<header class="header">Create New Category</header>
<%= render partial: "form" %>
<section class="sub-header"> <%= link_to "Back to Admin Dashboard", admin_dashboard_path %></section>

app/views/admin/categories/show.html.erb
<header class="header"><%= @category.name %></header>
<% @category.movies.each do |movie| %>
<section class="movie-card">
  <section class="movie">
    <center class="title"><%= link_to movie.title, movie_path(movie) %></center>
    <center><%= movie.description %></center>
  </section>
</section>
<% end %>

app/views/admin/images/_form.html.erb
<section class="form-container">
  <%= form_for ["admin", @image] do |f| %>

  <%= f.label :url %>
  <br>
  <%= f.text_field :url, :class => "form-field" %>

  <section class="submit-container">
    <%= f.submit :class => "submit-button" %>
  </section>

  <% end %>
</section>

app/views/admin/images/_nav.html.erb
<nav class="nav">
  <section class="nav-links">
    <%= link_to "Movies", movies_path %>
    <%= link_to "Categories", categories_path %>
  </section>
  <section class="nav-user">
    Welcome, <%= current_user.username %>!
    <%= link_to "My Movie Ideas", user_movies_path(current_user) %>
    <%= link_to "Admin Dashboard", admin_dashboard_path if current_admin? %>
    <%= link_to "Log Out", logout_path, method: "delete" %>
  </section>
</nav>

app/views/admin/images/index.html.erb
<header class="header">All Images</header>
<header class="sub-header">Not finding the image you want? <br><%= link_to "Create one here", new_admin_image_path %></header>
<section class="images">
  <% @images.each do |image| %>
  <section class="image">
    <%= image_tag("#{image.url}") %>
  </section>
  <% end %>
</section>

app/views/admin/images/new.html.erb
<header class="header">Upload from URL</header>
<%= render partial: "form" %>
<section class="sub-header"> <%= link_to "Back to Admin Dashboard", admin_dashboard_path %></section>

app/views/categories/_nav.html.erb
<nav class="nav">
  <section class="nav-links">
    <%= link_to "Movies", movies_path %>
    <%= link_to "Categories", categories_path %>
  </section>
  <section class="nav-user">
    Welcome, <%= current_user.username %>!
    <%= link_to "My Movie Ideas", user_movies_path(current_user) %>
    <%= link_to "Admin Dashboard", admin_dashboard_path if current_admin? %>
    <%= link_to "Log Out", logout_path, method: "delete" %>
  </section>
</nav>

app/views/categories/index.html.erb
<header class="header">All Categories</header>
<header class="sub-header">Movies Inside</header>
<section class="categories">
  <% @categories.each do |category|  %>
  <section class="category">
    <section class="category-title">
      <center><%= link_to category.name, category_path(category) %></center>
    </section>
  </section>
<% end %>
</section>

app/views/categories/show.html.erb
<header class="header"><%= @category.name %></header>
<% @category.movies.each do |movie| %>
<section class="movie-card">
  <section class="movie">
    <center class="title"><%= link_to movie.title, movie_path(movie) %></center>
    <center><%= movie.description %></center>
  </section>
</section>
<% end %>

app/views/users/_form.html.erb
<section class="form-container">
  <%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, :class => "form-field" %>
<br>
    <%= f.label :email %>
    <br>
    <%= f.text_field :email, :class => "form-field" %>

    <%= f.label :password %>
    <%= f.password_field :password, :class => "form-field" %>
    <section class="submit-container">
      <%= f.submit :class => "submit-button" %>
    </section>
  <% end %>
</section>

app/views/users/_nav.html.erb
<nav class="nav">
  <section class="nav-links">
    <%= link_to "Movies", movies_path %>
    <%= link_to "Categories", categories_path %>
  </section>
  <section class="nav-user">
    Welcome, <%= current_user.username %>!
    <%= link_to "My Movie Ideas", user_movies_path(current_user) %>
    <%= link_to "Admin Dashboard", admin_dashboard_path if current_admin? %>
    <%= link_to "Log Out", logout_path, method: "delete" %>
  </section>
</nav>

app/views/users/edit.html.erb
<header class="header">Edit Yourself</header>
<%= render partial: "form" %>
<footer></footer>

app/views/users/new.html.erb
<header class="header">Welcome! Sign up here</header>
<%= render partial: "form" %>
<footer></footer>

app/views/users/show.html.erb
<header class="header">Welcome <%= current_user.username %></header>
<header class="sub-header">You rated <%= current_user.total_ratings %> movie ideas!</header>
Go forth and rate movies!